#Generated Form Function
Add-Type -Name Window -Namespace Console -MemberDefinition '
[DllImport("Kernel32.dll")]
public static extern IntPtr GetConsoleWindow();
[DllImport("user32.dll")]
public static extern bool ShowWindow(IntPtr hWnd, Int32 nCmdShow);
'


$global:PSDefaultParameterValues = @{'Invoke-RestMethod:Proxy'='http://PRSM-SRVLIN1016:3128'}


function Hide-Console
{
    $consolePtr = [Console.Window]::GetConsoleWindow()
    #0 hide
    [Console.Window]::ShowWindow($consolePtr, 0)
}

function GenerateForm {
    ########################################################################
    # Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.9.0
    # Generated On: 15/03/2021 17:05
    # Generated By: dveg
    ########################################################################
    
    #region Import the Assemblies
    [reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
    [reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
    #endregion
    
    #region Generated Form Objects
    $form1 = New-Object System.Windows.Forms.Form
    $label3 = New-Object System.Windows.Forms.Label
    $label2 = New-Object System.Windows.Forms.Label
    $label1 = New-Object System.Windows.Forms.Label
    $button4 = New-Object System.Windows.Forms.Button
    $button3 = New-Object System.Windows.Forms.Button
    $button2 = New-Object System.Windows.Forms.Button
    $textBox3 = New-Object System.Windows.Forms.TextBox
    $textBox2 = New-Object System.Windows.Forms.TextBox
    $textBox1 = New-Object System.Windows.Forms.TextBox
    $button1 = New-Object System.Windows.Forms.Button
    $InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
    #endregion Generated Form Objects
    
    #----------------------------------------------
    #Generated Event Script Blocks
    #----------------------------------------------
    #Provide Custom Code for events specified in PrimalForms.
    $handler_button3_Click= 
    {
        $user = $textBox2.Text
        $userpassword  = $textBox3.text | ConvertTo-SecureString -AsPlainText -Force
        $passwordToEncrypt = $textBox1.Text 
        $creds = [System.Management.Automation.PSCredential]::new($user, $userpassword)
        $OpenFileDialog = New-Object System.Windows.Forms.SaveFileDialog
        $OpenFileDialog.initialDirectory = $initialDirectory
        $OpenFileDialog.filter = "All files (*.*)| *.*"
        $OpenFileDialog.ShowDialog() |  Out-Null
        $filename = $OpenFileDialog.filename
		$workingdirectory = split-path $filename
        $string = start-process -FilePath "powershell.exe" -Credential $creds -argumentlist "-Command ConvertTo-SecureString $passwordToEncrypt -AsPlainText -Force | ConvertFrom-SecureString | out-file $filename" -workingdirectory $workingdirectory
    }
    
    $handler_label1_Click= 
    {
    #TODO: Place custom script here
    
    }
    
    $button2_OnClick= 
    {
        $passwordToEncrypt = $textBox1.Text 
        $OpenFileDialog = New-Object System.Windows.Forms.SaveFileDialog
        $OpenFileDialog.initialDirectory = $initialDirectory
        $OpenFileDialog.filter = "All files (*.*)| *.*"
        $OpenFileDialog.ShowDialog() |  Out-Null
        $filename = $OpenFileDialog.filename
		$workingdirectory = split-path $filename
        start-process -FilePath "psexec.Exe"  -argumentlist "/accepteula -s -i powershell.exe -Command ConvertTo-SecureString $passwordToEncrypt -AsPlainText -Force | ConvertFrom-SecureString | out-file $filename" -workingdirectory $workingdirectory
    
    }
    
    $button4_OnClick= 
    {
        $form1.close()
    
    }
    
    $handler_button1_Click= 
    {
        if (-not (Test-Path "C:\windows\System32\PsExec.exe"))
        {
            $downloadpath = "C:\windows\temp"
            invoke-webrequest https://download.sysinternals.com/files/PSTools.zip -OutFile "$downloadpath\pstools.zip"
            Expand-Archive C:\temp\pstools.zip $downloadpath
            Copy-Item "C:\Windows\Temp\PsExec.exe" "C:\windows\System32"
        }
    }
    
    $OnLoadForm_StateCorrection=
    {#Correct the initial state of the form to prevent the .Net maximized form issue
        $form1.WindowState = $InitialFormWindowState
    }
    
    #----------------------------------------------
    #region Generated Form Code
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 134
    $System_Drawing_Size.Width = 506
    $form1.ClientSize = $System_Drawing_Size
    $form1.DataBindings.DefaultDataSourceUpdateMode = 0
    $form1.Name = "form1"
    $form1.Text = "Super Password Encryptor"
    
    $label3.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 9
    $System_Drawing_Point.Y = 64
    $label3.Location = $System_Drawing_Point
    $label3.Name = "label3"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 19
    $System_Drawing_Size.Width = 159
    $label3.Size = $System_Drawing_Size
    $label3.TabIndex = 9
    $label3.Text = "password"
    
    $form1.Controls.Add($label3)
    
    $label2.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 9
    $System_Drawing_Point.Y = 38
    $label2.Location = $System_Drawing_Point
    $label2.Name = "label2"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 20
    $System_Drawing_Size.Width = 159
    $label2.Size = $System_Drawing_Size
    $label2.TabIndex = 8
    $label2.Text = "user"
    
    $form1.Controls.Add($label2)
    
    $label1.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 9
    $System_Drawing_Point.Y = 12
    $label1.Location = $System_Drawing_Point
    $label1.Name = "label1"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 19
    $System_Drawing_Size.Width = 159
    $label1.Size = $System_Drawing_Size
    $label1.TabIndex = 7
    $label1.Text = "password to encrypt"
    $label1.add_Click($handler_label1_Click)
    
    $form1.Controls.Add($label1)
    
    
    $button4.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 387
    $System_Drawing_Point.Y = 91
    $button4.Location = $System_Drawing_Point
    $button4.Name = "button4"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 26
    $System_Drawing_Size.Width = 106
    $button4.Size = $System_Drawing_Size
    $button4.TabIndex = 6
    $button4.Text = "close"
    $button4.UseVisualStyleBackColor = $True
    $button4.add_Click($button4_OnClick)
    
    $form1.Controls.Add($button4)
    
    
    $button3.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 275
    $System_Drawing_Point.Y = 90
    $button3.Location = $System_Drawing_Point
    $button3.Name = "button3"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 28
    $System_Drawing_Size.Width = 106
    $button3.Size = $System_Drawing_Size
    $button3.TabIndex = 5
    $button3.Text = "encrypt as user ..."
    $button3.UseVisualStyleBackColor = $True
    $button3.add_Click($handler_button3_Click)
    
    $form1.Controls.Add($button3)
    
    
    $button2.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 141
    $System_Drawing_Point.Y = 90
    $button2.Location = $System_Drawing_Point
    $button2.Name = "button2"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 28
    $System_Drawing_Size.Width = 128
    $button2.Size = $System_Drawing_Size
    $button2.TabIndex = 4
    $button2.Text = "encrypt as system ..."
    $button2.UseVisualStyleBackColor = $True
    $button2.add_Click($button2_OnClick)
    
    $form1.Controls.Add($button2)
    
    $textBox3.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 174
    $System_Drawing_Point.Y = 64
    $textBox3.Location = $System_Drawing_Point
    $textBox3.Name = "textBox3"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 20
    $System_Drawing_Size.Width = 319
    $textBox3.Size = $System_Drawing_Size
    $textBox3.TabIndex = 3
    $textBox3.PasswordChar = "*"
    
    $form1.Controls.Add($textBox3)
    
    $textBox2.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 174
    $System_Drawing_Point.Y = 38
    $textBox2.Location = $System_Drawing_Point
    $textBox2.Name = "textBox2"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 20
    $System_Drawing_Size.Width = 319
    $textBox2.Size = $System_Drawing_Size
    $textBox2.TabIndex = 2
    
    $form1.Controls.Add($textBox2)
    
    $textBox1.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 174
    $System_Drawing_Point.Y = 12
    $textBox1.Location = $System_Drawing_Point
    $textBox1.Name = "textBox1"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 20
    $System_Drawing_Size.Width = 319
    $textBox1.Size = $System_Drawing_Size
    $textBox1.TabIndex = 1
    
    $form1.Controls.Add($textBox1)
    
    
    $button1.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 9
    $System_Drawing_Point.Y = 90
    $button1.Location = $System_Drawing_Point
    $button1.Name = "button1"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 28
    $System_Drawing_Size.Width = 126
    $button1.Size = $System_Drawing_Size
    $button1.TabIndex = 0
    $button1.Text = "install psexec"
    $button1.UseVisualStyleBackColor = $True
    $button1.add_Click($handler_button1_Click)
    
    $form1.Controls.Add($button1)
    
    #endregion Generated Form Code
    
    #Save the initial state of the form
    $InitialFormWindowState = $form1.WindowState
    #Init the OnLoad event to correct the initial state of the form
    $form1.add_Load($OnLoadForm_StateCorrection)
    #Show the Form
    $form1.ShowDialog()| Out-Null
    
    } #End Function
    
    #Call the Function
    Hide-Console
    GenerateForm
    
